insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Beer Group', '1 Dahle Place', '(497) 3264394', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Miller-Mann', '0791 Claremont Street', '(153) 6316642', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Hettinger-King', '90 Hooker Plaza', '(397) 7443399', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Watsica Inc', '2302 Blue Bill Park Alley', '(321) 8992592', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Willms-Roberts', '46783 Fuller Court', '(462) 2550870', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Lindgren-O''Kon', '31015 Melvin Terrace', '(355) 9025824', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Corwin Inc', '28 Sauthoff Circle', '(893) 4513140', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Ferry, Koelpin and Goyette', '2 Aberg Trail', '(766) 5868061', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Feest and Sons', '15628 Arizona Lane', '(938) 6300609', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Leannon, Gerlach and Romaguera', '58183 Thierer Circle', '(902) 1774111', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Wiza-Brakus', '63320 Fallview Place', '(997) 8392976', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Schultz-Tillman', '23 New Castle Drive', '(480) 5740523', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Botsford-Schamberger', '87378 Killdeer Road', '(726) 3640869', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Gutmann, Cormier and Stamm', '57 Maywood Alley', '(133) 8247927', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Koelpin-Towne', '18684 Maple Wood Street', '(106) 5472014', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Swift Inc', '6823 Emmet Drive', '(380) 3490667', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Veum Inc', '31 Di Loreto Circle', '(991) 3164211', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Wintheiser-Muller', '13 Hintze Point', '(752) 5077640', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Rodriguez, Torp and Hegmann', '933 Sunnyside Terrace', '(620) 8030916', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Rolfson Inc', '067 Huxley Place', '(908) 6224272', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Nikolaus, Kihn and Swaniawski', '40 Sycamore Point', '(960) 5388249', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Zulauf Inc', '33 Independence Pass', '(722) 4935996', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Murazik-Daugherty', '89 Cardinal Trail', '(668) 5067520', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Hackett, Vandervort and Reichert', '37240 Moulton Road', '(393) 8678865', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Wuckert, Dibbert and King', '2 Artisan Terrace', '(736) 2259115', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Hansen Inc', '7 Fordem Street', '(216) 8543053', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Graham-Cassin', '422 Sunbrook Street', '(216) 2521178', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Weber-Beier', '30 8th Hill', '(941) 6687163', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Dach, Lindgren and Wisoky', '29587 Glacier Hill Pass', '(459) 8498864', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Welch-Bogan', '0718 Fieldstone Alley', '(754) 4576830', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Franecki, Ernser and Franecki', '7 Anhalt Plaza', '(127) 9015376', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Homenick-Fahey', '15 Continental Crossing', '(969) 9392313', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Kshlerin, Torp and Armstrong', '5 Schmedeman Point', '(880) 3833901', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Hilll, Fay and Hackett', '9710 Monterey Plaza', '(768) 6681931', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Daniel, Hand and Sporer', '3594 Moose Lane', '(731) 2899947', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Muller Group', '2639 Memorial Circle', '(441) 7972394', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Bauch and Sons', '24481 Hooker Drive', '(217) 2055391', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Boehm, Bayer and Stiedemann', '08160 Shoshone Court', '(649) 5561458', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Huel-Jast', '8 Lighthouse Bay Park', '(951) 8470586', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Schaden LLC', '48522 Mariners Cove Road', '(295) 5036441', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Bergstrom, Kunde and Ryan', '6 Hollow Ridge Junction', '(656) 4611608', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Reynolds-Kunze', '2 Algoma Parkway', '(743) 4792091', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Bailey Inc', '033 American Ash Street', '(619) 8034277', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Lueilwitz-Balistreri', '52 Cardinal Plaza', '(287) 9609191', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Treutel-Hand', '0282 Londonderry Pass', '(323) 5378496', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Durgan-Durgan', '51 Thompson Hill', '(531) 7659632', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Murray Group', '307 Ruskin Road', '(205) 5192627', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Yundt LLC', '62077 Laurel Point', '(521) 8961260', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Daugherty Group', '561 Talisman Place', '(611) 2435321', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Schiller LLC', '26 Merchant Place', '(445) 2587268', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Fisher-Hammes', '4 Jana Plaza', '(702) 9091092', 3);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Monahan LLC', '06158 Harbort Junction', '(499) 9354641', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('DuBuque Group', '94 Towne Drive', '(615) 1078210', 1);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Crist, Lind and Volkman', '831 Monica Junction', '(689) 3594401', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Rosenbaum, Orn and Auer', '578 Dorton Trail', '(426) 7663512', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Jacobi-Medhurst', '6714 Main Drive', '(251) 6593701', 4);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Maggio LLC', '0 Hoepker Place', '(886) 1291294', 5);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Runolfsson-Bosco', '4426 Talmadge Road', '(871) 4383942', 0);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Fay, Hand and Kozey', '5 David Terrace', '(602) 8801662', 2);
insert into fornecedor (nome_forn, endereco , contato , avaliacao_forn) values ('Towne LLC', '10165 Sutteridge Court', '(516) 3184393', 5);
