insert into operador (nome_op, especializacao, disponibilidade) values ('Cherin Jone', 'Painter', '23:57');
insert into operador (nome_op, especializacao, disponibilidade) values ('Gabriele Coddrington', 'Ironworker', '14:10');
insert into operador (nome_op, especializacao, disponibilidade) values ('Torry Headan', 'Safety Officer', '21:03');
insert into operador (nome_op, especializacao, disponibilidade) values ('Keven Devin', 'Plumber', '6:17');
insert into operador (nome_op, especializacao, disponibilidade) values ('Paloma Danielsky', 'Plasterers', '6:08');
insert into operador (nome_op, especializacao, disponibilidade) values ('Jabez Mingay', 'Millwright', '22:52');
insert into operador (nome_op, especializacao, disponibilidade) values ('Wilie Starbeck', 'Millwright', '12:48');
insert into operador (nome_op, especializacao, disponibilidade) values ('Bondy McMichan', 'Electrician', '18:17');
insert into operador (nome_op, especializacao, disponibilidade) values ('Byrann Marxsen', 'Millwright', '0:33');
insert into operador (nome_op, especializacao, disponibilidade) values ('Nate Teliga', 'Laborer', '4:03');
insert into operador (nome_op, especializacao, disponibilidade) values ('Frances Munnery', 'Boilermaker', '15:02');
insert into operador (nome_op, especializacao, disponibilidade) values ('Giuditta Penswick', 'Pipefitter', '7:33');
insert into operador (nome_op, especializacao, disponibilidade) values ('Merline O''Lenane', 'Landscaper', '4:03');
insert into operador (nome_op, especializacao, disponibilidade) values ('Gabriel Roxburch', 'Ironworker', '21:49');
insert into operador (nome_op, especializacao, disponibilidade) values ('Rachael Snoden', 'Laborer', '12:48');
insert into operador (nome_op, especializacao, disponibilidade) values ('Belinda Horry', 'Linemen', '2:42');
insert into operador (nome_op, especializacao, disponibilidade) values ('Felicio Bourtoumieux', 'Concrete Finisher', '23:35');
insert into operador (nome_op, especializacao, disponibilidade) values ('Dotty Gallety', 'Electrician', '9:20');
insert into operador (nome_op, especializacao, disponibilidade) values ('Hector Sleigh', 'Landscaper', '7:03');
insert into operador (nome_op, especializacao, disponibilidade) values ('Shaina Blythin', 'Boilermaker', '0:47');
insert into operador (nome_op, especializacao, disponibilidade) values ('Tripp Appleford', 'Plasterers', '5:11');
insert into operador (nome_op, especializacao, disponibilidade) values ('Viole Meagh', 'Welder', '2:01');
insert into operador (nome_op, especializacao, disponibilidade) values ('Chickie Shimmings', 'Pipefitter', '23:47');
insert into operador (nome_op, especializacao, disponibilidade) values ('Orlando Pietzner', 'Linemen', '9:00');
insert into operador (nome_op, especializacao, disponibilidade) values ('Doreen Iban', 'Waterproofer', '19:35');
insert into operador (nome_op, especializacao, disponibilidade) values ('Lucias Terbeck', 'Safety Officer', '17:34');
insert into operador (nome_op, especializacao, disponibilidade) values ('Rollie Krzyzaniak', 'Refridgeration', '8:49');
insert into operador (nome_op, especializacao, disponibilidade) values ('Isadore Fearon', 'Millwright', '14:26');
insert into operador (nome_op, especializacao, disponibilidade) values ('Johnathon Attride', 'Painter', '17:17');
insert into operador (nome_op, especializacao, disponibilidade) values ('Amory Yerrell', 'Concrete Finisher', '14:03');
insert into operador (nome_op, especializacao, disponibilidade) values ('Tracy Mackie', 'Electrician', '8:42');
insert into operador (nome_op, especializacao, disponibilidade) values ('Latrina Grabham', 'Tile Setter', '3:16');
insert into operador (nome_op, especializacao, disponibilidade) values ('Norrie Conisbee', 'HVAC', '6:01');
insert into operador (nome_op, especializacao, disponibilidade) values ('Jeanelle O''Henehan', 'Laborer', '10:03');
insert into operador (nome_op, especializacao, disponibilidade) values ('Gail Pigny', 'Cement Mason', '12:29');
insert into operador (nome_op, especializacao, disponibilidade) values ('Denys Dahl', 'Pipefitter', '15:09');
insert into operador (nome_op, especializacao, disponibilidade) values ('Karrie Hothersall', 'Stucco Mason', '11:40');
insert into operador (nome_op, especializacao, disponibilidade) values ('Tracie Deerr', 'HVAC', '15:15');
insert into operador (nome_op, especializacao, disponibilidade) values ('Kathe Reggio', 'Painter', '15:57');
insert into operador (nome_op, especializacao, disponibilidade) values ('Broddy Trever', 'Carpenter', '15:43');
insert into operador (nome_op, especializacao, disponibilidade) values ('Genevra Lung', 'Terrazzo', '23:21');
insert into operador (nome_op, especializacao, disponibilidade) values ('Daren Doward', 'Brickmason', '14:55');
insert into operador (nome_op, especializacao, disponibilidade) values ('Shirleen Dummett', 'Electrician', '12:24');
insert into operador (nome_op, especializacao, disponibilidade) values ('Devan Gaynor', 'Refridgeration', '23:11');
insert into operador (nome_op, especializacao, disponibilidade) values ('Allin Boni', 'Equipment Operator', '2:02');
insert into operador (nome_op, especializacao, disponibilidade) values ('Marline Glavias', 'Landscaper', '20:19');
insert into operador (nome_op, especializacao, disponibilidade) values ('Roth Keers', 'Plumber', '19:46');
insert into operador (nome_op, especializacao, disponibilidade) values ('Maure Stapforth', 'Safety Officer', '11:59');
insert into operador (nome_op, especializacao, disponibilidade) values ('Yovonnda Oscroft', 'Landscaper', '23:18');
insert into operador (nome_op, especializacao, disponibilidade) values ('Bryna Lewing', 'Sheet Metal Worker', '7:09');
insert into operador (nome_op, especializacao, disponibilidade) values ('Maryanne Bartosch', 'Terrazzo', '1:21');
insert into operador (nome_op, especializacao, disponibilidade) values ('Vallie Cheltnam', 'HVAC', '3:00');
insert into operador (nome_op, especializacao, disponibilidade) values ('Faye Carnaman', 'Painter', '16:23');
insert into operador (nome_op, especializacao, disponibilidade) values ('Tessy Litt', 'Brickmason', '9:42');
insert into operador (nome_op, especializacao, disponibilidade) values ('Tawsha Calderwood', 'Carpenter', '11:45');
insert into operador (nome_op, especializacao, disponibilidade) values ('Haskel Sandeford', 'Ironworker', '15:38');
insert into operador (nome_op, especializacao, disponibilidade) values ('Curtis Jedraszczyk', 'Sheet Metal Worker', '4:42');
insert into operador (nome_op, especializacao, disponibilidade) values ('Travers Schutt', 'Tile Setter', '13:35');
insert into operador (nome_op, especializacao, disponibilidade) values ('Claiborne Alloisi', 'Painter', '5:57');
insert into operador (nome_op, especializacao, disponibilidade) values ('Bonni Grassi', 'Concrete Finisher', '14:17');
